print('Hello')
print("Hello, World!")
print("Hello 'World!'")
print('Hello "World!"')

print('Hello ' + 'world!')
print('Hello ' * 3)
print('Hello ' [0])
print('Hello ' [1])
print('Hello ' [2])
print('Hello ' [3])
print('Hello ' [4])
print('Hello ' [5])

print('hello world!'.capitalize())
print('hello world!'.upper())
print('Hello world!'.__len__())
print(len('Hello world!'))
print('Hello world!'.replace(' world!', ', Python!'))

print("pxzhu's \"tutorial\"")
print("\\")
print("Hello \nWorld!")
print("Hello \tworld")
print("\a")
print('Hello \nWorld!')

print(10 + 5)
print("10" + "5")